services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=property_db
      - POSTGRES_USER=property_user
      - POSTGRES_PASSWORD=property_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-caching

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/var/lib/redis/data
    networks:
      - backend-caching

volumes:
  postgres_data:
  redis_data:

networks:
  backend-caching:
    driver: bridge
