services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=property_db
      - POSTGRES_USER=property_user
      - POSTGRES_PASSWORD=property_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:lates
    ports:
      - '6379:6379'

volumes:
  postgres_data:

networks:
  backend-caching:
    driver: bridge
