services:
  app:
    build: .
    command: >
      sh -c "
        echo 'Collecting static files ...' && 
        python manage.py collectstatic --noinput &&
        echo 'Starting Gunicorn ...' &&
        gunicorn alx_backend_caching_property_listings.wsgi:application --bind 0.0.0.0:8000
      "
    #  |
    #   gunicorn \
    #   alx_backend_caching_property_listings.wsgi:application \
    #   --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-caching

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/var/lib/redis/data
    networks:
      - backend-caching

volumes:
  postgres_data:
  redis_data:

networks:
  backend-caching:
    driver: bridge
